export const social = [
  {
    id: 1,
    img: "/Icons/facebook-icon.svg",
    alt: "facebook",
  },
  {
    id: 2,
    img: "/Icons/instagram-icon.svg",
    alt: "Instagram",
  },
  {
    id: 3,
    img: "/Icons/linkedin-icon.svg",
    alt: "Linkedin",
  },
  {
    id: 4,
    img: "/Icons/reddit-icon.svg",
    alt: "Reddit",
  },
  {
    id: 5,
    img: "/Icons/Tiktok-1.svg",
    alt: "Tiktok",
  },
  {
    id: 6,
    img: "/Icons/X-Logo-Green.svg",
    alt: "X-Logo",
  },
  {
    id: 7,
    img: "/Icons/youtube-icon.svg",
    alt: "Youtube",
  },
];

export const footer = [
  {
    id: 1,
    para: "Integrations",
    data: [
      "Shopify",
      "Etsy",
      "eBay",
      "Amazon",
      "TikTok Shop",
      "PrestaShop",
      "BigCommerce",
      "Wix",
      "WooCommerce",
      "Squarespace",
      "Printify API",
      "Printify Pop-Up Store",
      "Shutterstock",
    ],
  },
  {
    id: 2,
    para: "Discover",
    data: [
      "Blog",
      "Guides",
      "Products",
      "Etsy print-on-demand",
      "Shopify print-on-demand",
      "Woocommerce print-on-demand",
      "Wix print-on-demand",
      " Squarespace print-on-demand",
      "Make Your Own Shirt",
      " Brands",
      "Pricing",
      "Shipping Rates",
      "Mockup Generator",
    ],
  },
  {
    id: 3,
    para: "Start selling",
    data: [
        'Custom T-shirts',
        'Custom Hoodies',
        'Custom Mugs',
        'Custom Socks',
        "Custom Backpacks",
        'Custom Branding',
        'Sell on Etsy',
        'Sell on Social Media',
        'Free T-shirt Designs',
        'Custom Products',
       ' Custom All-Over-Print Hoodies',
        'Start a Clothing Line',
        'Start POD Business',
        'Bulk Orders',
        'Transfering To Printify'
    ],
  },
  {
    id: 4,
    para: "Printify",
    data: [
       ' Print on Demand',
        'Print Providers',
        'Experts Program',
        'Printify Express Delivery',
        'Become a Partner',
        'About',
        'Printify Quality Promise',
        'Jobs',
        'Webinars',
        'Printing Profits Podcast',
        'Contact Us',
        'Affiliate',
        'Contact Sales',
        'POD Glossary',
        'Network Fulfillment Status',
        'Merchant Protection',
        'Security',
        'Sitemap',
    ],
  },
];

//
